os: osx
before_install:
  - git clone https://github.com/henrydobson/luggage.git ~/henrydobson/luggage
  - cd ~/henrydobson/luggage
  - make bootstrap_files
  - cd ~/henrydobson/OSX_Hiera
script:
  - sudo make pkg
  - sudo installer -pkg Desktop/hiera*.pkg -target /
